Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu2204"

  config.vm.network "private_network", ip: "192.168.121.100", type: "dhcp"

  config.vm.provider :libvirt do |kvm|
    kvm.memory = 2048
    kvm.cpus = 2
  end

  config.vm.synced_folder "../", "/app", type: "rsync"

  config.vm.provision "shell", path: "bootstrap.sh"
end
