"""Initial migration

Revision ID: 7d72c50849a1
Revises:
Create Date: 2026-02-06 18:20:01.997552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d72c50849a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'first_name', sa.String(
                            length=50), nullable=False),
                    sa.Column(
                        'last_name', sa.String(
                            length=50), nullable=False),
                    sa.Column('grade', sa.String(length=5), nullable=False),
                    sa.Column('email', sa.String(length=120), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    # ### end Alembic commands ###
